name = "Shot"
uuid = "f16cb476-2844-4d12-b034-43fe284cab7e"
authors = ["Leytzher Muro"]
version = "0.1.0"

[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"

[compat]
StatsPlots = "0.14"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
